### ISSUE TITLE
Thanks and tooltip info not refreshing after operation.

### ISSUE THREAD

**Issue by somebadhat** [bricelam/ImageResizer#138]
Great work.  
I thought your tool had failed because the tooltip info does not refresh w/o F5.  It took me 10 minutes to figure out it was working.  You should refresh the tooltip info.

![00058 jpg at 07 07 AM](https://user-images.githubusercontent.com/18543502/61873535-c9375c80-aeab-11e9-81ac-c056f9529e27.JPG)

![00058 jpg at 07 07 AM 002](https://user-images.githubusercontent.com/18543502/61873434-9d1bdb80-aeab-11e9-8fa1-d478d65d0ca6.JPG)

**Comment by JNavas2** [comment]
I think this is actually a (long-standing) Windows issue.
Probably for performance reasons, Windows doesn't keep the desktop refreshed.
When you press F5, you are refreshing the Desktop.

**Comment by somebadhat** [comment]
Are you saying ImageResizer can't be written to issue a command to refresh after it completes it's operations?

**Comment by JNavas2** [comment]
@somebadhat 
> Are you saying ImageResizer can't be written to issue a command to refresh after it completes it's operations?

I neither said nor even implied that, and to be clear, I don't speak for Brice.
It is, nonetheless, definitely a Windows issue*, rather than an IR issue.
For example, while encoding video files to the desktop with HandBrake,
the Windows pop-up is usually much different from the current file Properties.
And your suggested work-around might have drawbacks.
The simple alternative is to open File Properties (e.g., Alt-click).

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
