### ISSUE TITLE
Command-line parameters

### ISSUE THREAD

**Issue by bricelam** [bricelam/ImageResizer#14]
Image files and the output directory can already be specified, but allowing the size and other options to be specified would enable a lot of automation scenarios.

**Comment by ITJoePC** [comment]
Thank you for this great tool!  I just used it to scale down a bunch of unnecessarily large photos in SharePoint.  I found that accessing SharePoint through WebDAV did not always work (or maybe I was not patient with SP to refresh).    I also found a few pages with broken "<img...>" references to JPG files containing ".bak" in the name that I had to change back.  SharePoint auto-updates references to files & folders throughout the site.  I assume it didn't get changed back after it was renamed to the original name (overwriting).  I ended up copying them out of the SharePoint folder and back in to solve the issue.

Re: "automation scenarios."  One tedious thing was going through each folder to select all & right click, instead of being able to right click the folder and it would iterate the tree.  I know that would require some assumptions about what files to attempt to process (perhaps all supported image files, as a right click option).
 
This could possibly be broken up into two issues, but I wanted to give some background.  Let me know if you want me to break this up and create one or two of them as new issues.

**Comment by JNavas2** [comment]
@ITJoePC 
Why not use Windows Explorer to search a subtree for images
you want to resize, select them all, and Resize them?

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
