### ISSUE TITLE
Checkbox instead of radio button

### ISSUE THREAD

**Issue by mrmowji** [bricelam/ImageResizer#144]
First of all thanks for this minimal useful software. I couldn't find this simple batch resizing in any of graphic softwares that I work with.
I have a suggestion. Sometimes we need to have multiple target sizes (e.g. different icons for different use cases). That'd be great if the user could simply check all the desired sizes they want and get the resized files with one click.

**Comment by JNavas2** [comment]
Even though I've not felt the need, at first blush I liked the idea, but on reflection, I see some issues:
1. Conflicts with "Resize the original pictures", which I often use.
2. Makes any size change a 2 click rather than a 1 click operation, a negative.
3. Likely to confuse new users, leading to frustration and complaints.

Consequently, I would only like to see this as an Advanced option.

**Comment by mrmowji** [comment]
@JNavas2 Thanks for your opinion.

1. I guess it wouldn't conflict. You only need to resize the original picture, when you need only one size. In this case, you'd select only one size, not many.
2. Number of clicks wouldn't change. If it's an already selected size, you're good to go (1 click on Resize button). If you need a new size, you need to select it (2+ clicks). That's what we have now.
3. Not sure how. :D

But I think it's better to put it in Advanced options like you said.

**Comment by JNavas2** [comment]
1. It conflicts because the option is not valid when 2 sizes are selected. Code would be needed to disable the option when/if multiple sizes are selected, and that might cause confusion/frustration.
2. Number of clicks _would_ change. Currently a change of size is only one click of the new size. With checkboxes, it's 2 clicks, with the additional click to _deselect the old size_.
3. Current behavior is simple: choose the size. New behavior would risk _inadvertently_ selecting more than one size, likely resulting in confusion/frustration.

**Comment by mrmowji** [comment]
1. So it's a confusion, not a conflict; there's a workaround as you mentioned. I still don't see it as a confusion.
2. You're right. We can use **presets** which contain one or more sizes inside them and use radio buttons. This way we have the same number of clicks as before, but defining presets would need some clicks and that's a one-time thing. I think it's better than checkboxes.
3. "Inadvertently selecting more than one" is just checkboxes' thing. We can't stop using checkboxes because someone might inadvertently select more than one option. Buttons could be clicked inadvertently too.

**Comment by JNavas2** [comment]
@mrmowji,

My points are based on well-established UX principles. (UX = [User eXperience](https://www.nngroup.com/articles/definition-user-experience/), which encompases UI, User Interface) When more stuff (options, choices, even just text) is added to an interface, comprehension and efficiency go down, confusion and frustration go up. It's why [PowerPoint slides should be kept simple](https://www.slidegenius.com/blog/simplicity-powerpoint-slides).

1. It's a _conflict_ unless it's disabled, and when users are confronted with things that aren't applicable, _confusion_ inevitably results. Even dynamic disable would lead to confusion, because some people would not understand _why_ it is being disabled. 
2. Yes, Custom multi-size presets (Advanced Option) could work. Then the question is whether or not enough people would benefit to justify the extra work and complexity. My guess is that less than 10% of users would actually take advantage of the feature, but that's just a guess.
3. Actually we can and should avoid UI elements that increase confusion and frustration, in part because it hurts the reputation of the software, in part because it increases support hassles. The best UI is clear and simple. The option to _Ignore the orientation of pictures_, for example, has caused confusion and frustration.

Hope that helps,
John

**Comment by mrmowji** [comment]
@JNavas2 Thanks. I'm actually a minimalist and familiar with some UX principles, and I don't like cluttered UIs, and by clutter I mean being there for no reason or no use for most users. On the other hand, UX must be done based on the needs. One rule is DRY (don't repeat yourself). Repeating ourselves could be a bigger frustration. If most users need to do the same job over and over again to achieve what they want, I guess adding some text or element to prevent that wouldn't hurt the project.
That was a suggestion. If something is useful to most users I think we should negotiate its existence. I hope there is some way to find out what % of users really need this.

**Comment by JNavas2** [comment]
@mrmowji It's now in Brice's capable hands.

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
