### ISSUE TITLE
Delete picture

### ISSUE THREAD

**Issue by Keuronde** [bricelam/ImageResizer#18]
If you check the two last checkbox:

* Replace original files
* Ignore rotation

And that you try to resize a picture that is in one of the library folder (eg: Library/Images) the file is sent to the trash bin

**Comment by CharlesVidal** [comment]
@Keuronde It seems like the image you are resizing is on the desktop and it isn't refreshing. If you navigate to "C:\Users\YOURUSERNAME\Desktop" you will be able to find the file in the file explorer. It sends the other to the recycle bin because you chose to replace the original file. It isn't ideal but while on the desktop press F8 and this should refresh the desktop for you and reveal that missing file. You can do the same in any file explorer window but I've never seen that problem outside of things being saved to the desktop. Hope this helps!

**Comment by bricelam** [comment]
Files will not be send to the recycle bin unless they are successfully resized. Closing as external since I believe you are experiencing the know issue described by @CharlesVidal.
