### ISSUE TITLE
More filename parameters

### ISSUE THREAD

**Issue by bricelam** [bricelam/ImageResizer#19]
Version 3.1.0 supports the following parameters:
- Original filename
- Size name
- Size width
- Size height

There are other parameters that may be useful, but I'll wait for more feedback (comment below) before adding them. Ideas:
- Size unit (pixels, inches, etc.)
- Actual width
- Actual height

**Comment by avatarium** [comment]
nice little tool but it would be even better with JPEG quality level and custom filename ;)

**Comment by Akxe** [comment]
Found one that could be great, the `size name`. Since you can create custom sizes, I have sizes as `big`, `big/goal`, `small`, `small/goal`. And folder are as fallow:

- big
    - goal
- small
   - goal
- orig
    - goal

Therefor I would love to use `../%size/$name` as file output...

Also using strings instead of numbers for specification of what it will be replaced with seems better to me

**Comment by JNavas2** [comment]
FWIW, I'm happy with the current system.

**Comment by bricelam** [comment]
I added the actual width/height (in pixels) to the available parameters in version 3.1.0-beta2. I'll close this issue, but feel free to file new ones for any additional parameters you need in your workflows.

**Comment by Akxe** [comment]
@bricelam How about my idea? I am not telling it would be neccesary to be added, but I would like to know your opinion on this (named group, size name)

**Comment by bricelam** [comment]
It should already be possible using `%2\%1`. If it doesn't work, file a bug.
