### ISSUE TITLE
Profile-based encoding / level of compression

### ISSUE THREAD

**Issue by IgitBuh** [bricelam/ImageResizer#20]
It would be very helpful if the profiles (Small, Medium, Large, etc.) would not only include the height and width, but also the level of compression. Right now you're planning to have the encoding value to be global for all profiles. I recommend to allow custom encoding values for each profile.

For example I'd like to have my "Small"-profile with a JPEG quality level of "70" for quickly sending them as email attachments. But I'd also like to have an "Archive"-profile where the size is reduced to 50% with a JPEG quality level of 95%. I'd use this profile for archiving unimportant photos from my DSLR camera to save space, without giving up too much of the image quality.

**Comment by bricelam** [comment]
There are [many wonderful alternatives](http://alternativeto.net/software/image-resizer-powertoy-clone/) to this utility that provide the rich feature set you are looking for.

As a principle, I refuse to add additional options to the main window. I am also against adding it to the Sizes tab on the Advanced Options window since this would break parity with the Custom size.

I am closing this as wontfix. Sorry to be dogmatic, but I have a responsibility to keep the utility simple.

In 3.1, you'll be able to set the quality level globally in the Advanced Options page.

![advanced_encoding](https://cloud.githubusercontent.com/assets/1226749/19281764/90a2bb80-8fa0-11e6-88e4-f446c8c5dce4.png)
