### ISSUE TITLE
Image Resizer reports not enough memory

### ISSUE THREAD

**Issue by archfrog** [bricelam/ImageResizer#26]
I'm trying out Image Resizer for the first time.  I select 28 files in Windows Explorer, then click the "Resize pictures" context menu, then select the smallest size and tell Image Resizer to only shrink the files.

I get the following error message (translated from Danish):

    Resize completed with problems
    021.png
    Not sufficient memory to complete the program.
    015.png
    Not sufficient memory to complete the program.
    028.png
    Not sufficient memory to complete the program.

The files are no secret as they are part of a public article on the Internet so I have attached them in an archive.  Try uncompressing the archive and then select all the images and resize them to the smallest size.

[tinified.zip](https://github.com/bricelam/ImageResizer/files/563234/tinified.zip)

My system has 16 GB RAM of which some 6 GB are currently free.  Besides it has a huge swap file.

Windows 8.1 Home x64 Danish.  

Windows %TEMP% is located on a RAM disk with about 1.8 gigabyte free space.  This may be the culprit but if so, I guess Image Resizer is resizing all pictures before deleting the originals and also is using a lot of space just for resizing.

**Comment by bricelam** [comment]
Have you tried this in [v3.1.0-beta1](https://github.com/bricelam/ImageResizer/releases/tag/v3.1.0-beta1)? It should use less memory.

**Comment by archfrog** [comment]
No, I had an urgent need to convert some images, so I did it manually in Paint.NET.  I no longer have any particular need for batch converting images, so I am no longer using ImageResizer.

**Comment by JNavas2** [comment]
> @archfrog
1. Why would you only have 6 GB free (even with a 2 GB RAMDISK)?
My 16 GB system normally runs with about 13 GB available. 
2. I see no significant memory utilization bump by Image Resizer.
Your sample images converted instantly without any issues.
3. .NET applications tend to be sluggish as compared to native apps.
4. I've never seen that error with any version of Image Resizer,
even on a system with 8 GB.
5. Locating temp files on a ramdisk is usually a poor use of resources.

**Comment by archfrog** [comment]
1. Probably due to Samsung Magician, which uses excess RAM for buffering SSD data.
2. Great :-)
3. I've done .NET apps for a decade, they usually run well on fast Windows machines.  Got a 4 GH box.
4. I consistently had the error, otherwise I wouldn't have reported it.
5. I've been using Windows since 1991 and locating temp files on a RAM disk works very well for me.  For instance, Google Chrome starts up instantly and I like that.  I like that my temp dir doesn't gradually grow to 1-2 gigabytes because Windows is too daft to empty it on boot like *nix does.

One possibility is that the problem was caused by Samsung Magician or my deliberate setup with temp files on a RAM disk.  I've seen other peculiarities over the years, such as apps with integrated Explorer windows not refreshing proberly even when you manually hit F5 in the respective window.  I usually attribute these pecularities to Samsung Magician, but don't know for sure if that is indeed the culprit.

**Comment by JNavas2** [comment]
1. Depending on how you use your system, taking RAM away from applications and OS caching may be counterproductive. I likewise have a Samsung SSD, but don't keep Magician installed because my system performs better overall without it. For reasons of performance and stability, I minimize things running in the background.
2. Wasn't bragging, just reporting.
3. That's faster than my 3 GHz ThinkPad, but I see the lag of .NET apps even on hexa-core, overclocked, water cooled, 4 GHz engineering workstations.
4. Sure, just reporting. You seem to have a particular system issue that would be good to nail down.
5. Google Chrome starts instantly here too even with no RAM disk. It runs in the background by default. And I use a scheduled task to clean out my TEMP directory on a weekly basis. Emptying on every boot has some downsides.

**Comment by archfrog** [comment]
1. I'll consider it and try it out.  I find that Samsung Magician is particularly good when you copy stuff around and I also use VeraCrypt on a 9 GB volume, which works very fast with Magician.
2. No, didn't think you were :-)
3. You might want to try out "ngen" (to generate "native" code), but I largely agree that the big problem with .NET is that it is not native performance.  On the other hand, I think Paint.NET runs really well, especially compared to the built-in Paint application, which is a crude joke on the users of Windows.
4. Yes, I'll try running a month or two without Magician, it might very well fix the issues.
5. I never run Chrome in the backgrund because of possible security implications of long running JavaScript scripts.  Also had some other issues, long ago, with Chrome in the background.

Thanks for your input, I'm away on holiday right now, but will try it out when I get home.

**Comment by JNavas2** [comment]
1. My Samsung SSD is 1 TB, which has a large on-board RAM cache, so I only see copy slowdowns on huge (many GB) files. Why would you use VeraCrypt instead of Opal in hardware?
2. 
3. Windows Paint is of course pathetic. I use Adobe apps for my professional photography. For batch operations I sometimes use IrfanView or ImageMagick.
4. 
5. When you close all Chrome browser windows and tabs, the part that runs in the background is just the core, no JavaScript.
Enjoy your holiday!

**Comment by archfrog** [comment]
1. Mine's only 512 GB, but I think it has an adequate on-board RAM cache.  I use VeraCrypt because I store the VeraCrypt container in a Dropbox folder and then sync to all my machines at home, work, and holiday (where I use a tiny laptop only).  This allows me to access my personal files from virtually any place and OS without having to worry what happens if the SSD itself dies on me (I've tried that a few times too).  At the same time, I can rest peacefully knowing that Dropbox employees and NSA cannot read my oh-so-personal files :-)
...
5. Okie :-)  I'll try it out again, just recall having had some long forgotten issues with it.

Thanks!

**Comment by JNavas2** [comment]
1. Makes sense. Nicely done. I use Synology NAS with secure remote access.

**Comment by JNavas2** [comment]
Here's a Task Scheduler task that will clean the TEMP directory on system startup:
[Clean TEMP.zip](https://github.com/bricelam/ImageResizer/files/805745/Clean.TEMP.zip)
