### ISSUE TITLE
Option to remove metadata

### ISSUE THREAD

**Issue by bricelam** [bricelam/ImageResizer#3]
By stripping all but the essential metadata from the images, the resulting file size should be significantly smaller.

**Comment by bricelam** [comment]
WIC is a fickle beast. I looked into this but decided it was outside the scope of this utility. There are plenty of file-size-reducing utilities out there.

**Comment by schmoggles** [comment]
Looking forward to this feature Bricelam!  Love the simple and quick implementation of Image Resize - and with the option to remove (perhaps edit) the EXIF meta data, it will be the only "right-click" application out there that combines these simple needs!  I realize I can get similar results via windows properties, after resizing... but that's way more clicks.

**Comment by SusanKenneth** [comment]
I would love the possibility to remove all metadata 😍

**Comment by IgitBuh** [comment]
+1
I was actually surprised to see that the EXIF data remained in the resized copy. It should definitely be removed - for size and privacy reasons.

**Comment by JNavas2** [comment]
> I was actually surprised to see that the EXIF data remained in the resized copy. It should definitely be removed - for size and privacy reasons.

-1 (strongly disagree)

**Comment by IgitBuh** [comment]
It's not very constructive to just "strongly disagree" without giving any reasons.
Don't you want to have a smaller file size or don't you want to hide private details (GPS coordinates, EXIF fingerprinting, ...)?

I've tried "JPEG & PNG Stripper" (http://www.steelbytes.com/?mid=30) and removed all metadata from an image file produced by ImageResizer. The result was 24 KB smaller. This means that almost a fourth of a 100 KB image file is wasted.

Anyway, this could be optional to serve different purposes.

**Comment by JNavas2** [comment]
We'll have to agree to disagree on what makes for a constructive comment. But since you asked:
- In most cases the size difference is immaterial.
- Removal of _all_ EXIF data makes images less usable.
- All or nothing removal option would be like brain surgery with a chainsaw.
- EXIF data is more effectively manipulated with a tool designed for that purpose.

**Comment by samdx** [comment]
Hi,
Any update available?
Should be an option to remove the EXIF data when needed?
Seeking for the update.
Thanks.

**Comment by JNavas2** [comment]
[How Do I Get Rid of EXIF Metadata?](https://us.norton.com/internetsecurity-how-to-how-to-remove-gps-and-other-metadata-locations-from-photos.html)

Windows Explorer makes it easy to delete EXIF metadata from one photo or an entire batch of photos at once. Follow these steps:

1. Open the folder containing your image files.
2. Select all the files you want to delete EXIF metadata from.
3. Right-click anywhere within the selected fields and choose “Properties.”
4. Click the “Details” tab.
5. At the bottom of the “Details” tab, you’ll see a link titled “Remove Properties and Personal Information.” Click this link.
6. Windows will ask whether you want to make a copy of the photo with this information removed, or if you want to remove the information from the original. Choose the option you prefer and click “OK.”

**Comment by samdx** [comment]
@JNavas2 Thanks. Yes, it works great.
Just don't want to select then click and click again and again.

**Comment by JNavas2** [comment]
I'm still against it, for [reasons I listed previously](https://github.com/bricelam/ImageResizer/issues/3#issuecomment-382562162).
See [my prior post](https://github.com/bricelam/ImageResizer/issues/3#issuecomment-412964151) for how to easily remove metadata in Windows Explorer.

**Comment by JNavas2** [comment]
@IgitBuh 
1. You've likewise made your points already.
2. Like you, I'm just expressing my own opinions, without "force".
3. Everyone is indeed free to state their own opinions here, including both of us.
4. But negative personal comments are not appropriate.
5. Let's agree to disagree but with mutual respect.

**Comment by Surfingserenity** [comment]
I likewise would love this feature, it's available on many resize utilities(albeit non as handy as ImageResizer) and hence the usefulness of removing metadata from images is indisputable. 

Here's to hoping @JNavas2 doesn't try flog a dead horse by reiterating his pointless "tip" for the 4th time on this thread. Yes we know there's many different ways to remove metadata or we could use a different resizer all together to remove metadata but doing that would nullify the advantages of ImageResizer, which is a quick and convenient right click away. You have the right to your opinion but if Brice would be so kind as to add this feature why rain on everyone else's parade, it's not going to hurt you if it's added, just don't use the feature, simple.

Actually I find this feature would be especially handy in ImageResizer because I typically use it for pics I want to quickly share on social media and would prefer no metadata is included(often some metadata I add may contain info I would rather not share and hence for safety reasons would prefer all metadata removed for some pics), for more important posts I'll use Lightroom to export the image sizes I need and there I can customize the metadata included on export.

**Comment by JNavas2** [comment]
@Surfingserenity 
1. Your personal attack is silly, childish, inappropriate, pointless, and counterproductive.
2. I strongly oppose _feature creep_ because it contributes to code bloat, instability, complexity, and diverts resources from the basic purpose.
3. ImageResizer is "handy" _because_ it's a _one trick pony_—it's does one thing very well, fast and efficiently.
4. Where will it stop? You want one thing; someone else wants something else, and soon we would have a Swiss Army knife like [IrfanView](https://www.irfanview.com/), _which will do what you want_.

**Comment by Surfingserenity** [comment]
@JNavas2 you have some weird vendetta against anyone who doesn't agree with you, learn to relax, no one is "attacking" you and fortunately the only childish person on this thread is yourself. 

Just because ImageResizer suits you down to the ground as it is does not preclude useful additions that may help leagues of other users. Metadata removal is core functionality of resizing seeing that is needed almost solely at time of image resizing. Being a resizing tool it is most pertinent to ImageResizer.

Brice is the coder let him make the call if and when metadata removal may be added as a feature. He knows the in's and outs of his code and whether metadata removal will or will not add an undue burden to his work. I'm pretty sure Brice appreciates your input but doesn't need you to hold his hand.
Go well

**Comment by PermaPain** [comment]
yay

**Comment by Surfingserenity** [comment]
Still waiting and hoping this vital feature is implemented, thanks to Brice for reopening this.

**Comment by JNavas2** [comment]
As before, I vote no.
It's neither necessary nor appropriate, much less vital.
This is ImageResizer, not IrfanView.

**Comment by IgitBuh** [comment]
@JNavas2 You told your opinion multiple times now. We got it. Let other people have their opinions. You're not a doorman.
The mere fact that people keep asking for this feature should be enough indication that there is a need for it. Even if you do not need this feature.
Rest assured: Nobody will force you to use this function (should it ever come).

**Comment by JNavas2** [comment]
@IgitBuh 
Please stay on topic and stop trying to shut me up.
I have as much right to express my opinion here as you or anyone else,
and these personal attacks are what got the topic locked in the first place.

**Comment by Surfingserenity** [comment]
> 
> 
> As before, I vote no.
> It's neither necessary nor appropriate, much less vital.
> This is ImageResizer, not IrfanView.

Lol, thanks for the clarification, your input is much appreciated. 😂😂😂

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
