### ISSUE TITLE
Allow selecting a Language

### ISSUE THREAD

**Issue by bricelam** [bricelam/ImageResizer#55]
This would help anyone wanting to use a different language than their Windows language.

**Comment by bricelam** [comment]
Note, the utility currently shows whatever default Windows language you're using. To change it in Windows 10, go to **Windows Settings** > **Time & Language** > **Region & Language**, select (or add) your desired language, and click **Set as default**.

**Comment by thoral** [comment]
Although I prefer to have German as the default setting in Windows, I prefer to use some tools in their native language, i.e. mostly in English. Why? Because the German translations are sometimes terrible or ugly or not adequate or simply wrong. So an option to change the language on a per program base is often very useful.

**Comment by bricelam** [comment]
## Moved to Microsoft PowerToys

All future bug fixes, enhancements, and releases of Image Resizer for Windows will be done as part of the Microsoft PowerToys project.

If this is still something you'd like to see done, please follow up on [microsoft/PowerToys](https://github.com/microsoft/PowerToys)
